echo which system is used (dev/local/prod)

diff --git a/start-omp b/start-omp
--- a/start-omp
+++ b/start-omp
@@ -1,14 +1,14 @@
 #!/bin/bash
 
-if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ])
+if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ] && [ $1 != "local" ])
     then
-        echo "Parameter 'dev' oder 'prod' missing"
+        echo "Parameter 'dev' or 'prod' or 'local' missing"
         exit 0
 
-elif [ $1 == "dev" ]
+elif [ $1 == "dev" ] || [ "$1" == "local" ]
     then
-        echo start docker-compose dev
-        docker-compose -f docker-compose-ompdev.yml -p $1 up -d
+        echo start docker-compose $1
+        docker-compose -f docker-compose-omp$1.yml -p $1 up -d
 
 elif [ $1 == "prod" ]
     then
