improve start stop

diff --git a/stop-omp b/stop-omp
--- a/stop-omp
+++ b/stop-omp
@@ -1,18 +1,20 @@
-#!/bin/bash                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ])                                                                                                                                                                                         then                                                                                                                                                                                                                                             echo "parameter 'dev' oder 'prod' fehlt "                                                                                                                                                                                                    exit 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif [ $1 != "dev" ]                                                                                                                                                                                                                             then                                                                                                                                                                                                                                             docker-compose -f docker-compose-omp-ulb.yml -p $1 down                                                                                                                                                                                      docker-compose -f docker-compose-omp-ulb.yml -p $1 up -d                                                                                                                                                                                                                                                                                                                                                                                                                          elif [ $1 != "prod" ]                                                                                                                                                                                                                            then                                                                                                                                                                                                                                             docker-compose -f docker-compose-ompdev-ulb.yml -p $1 down                                                                                                                                                                                   docker-compose -f docker-compose-ompdev-ulb.yml -p $1 up -d                                                                                                                                                                                                                                                                                                                                                                                                                       fi  
+#!/bin/bash
+
+set -e 
 
 if  [ -z "$1" ] || ([ $1 != "dev" ] && [ $1 != "prod" ] && [ $1 != "local" ])
     then
-        echo "Parameter 'dev' oder 'prod' oder 'local' fehlt"
+        echo "parameter 'dev', 'prod' or 'local' is missing"
         exit 0
 
 elif [ "$1" == "dev" ] ||  [ "$1" == "local" ]
     then
-        echo stop docker-compose $1
+        echo "stop docker-compose $1"
         docker-compose -f docker-compose-omp$1.yml -p $1 down
 
 elif [ $1 == "prod" ]
     then
-        echo stop docker compose
+        echo "stop docker compose $1"
         docker-compose -f docker-compose-ompprod.yml -p $1 down
 fi
 
